version: '3.4'
services:
  pg-cep:
    image: "postgres:11"
    container_name: "pg-cep"
    ports:
      - "3306:33060"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  api-cep-java:
    container_name: api-cep-java
    build:
      context: .
      dockerfile: apiCep.Dockerfile
    depends_on:
      - pg-cep
    ports:
      - "8080:8080"
    environment:
      - NOOP=
      - DB_URL=pg-cep:33060
volumes:
  my_dbdata: