server:
  port: 8080
spring:
  application:
    name: cep
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driverClassName: org.postgresql.Driver
    password: 123
    username: usertest
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:33060}/dbcep
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
